DROP TABLE IF EXISTS Uses;
DROP TABLE IF EXISTS Researcher;
DROP TABLE IF EXISTS Mission;
DROP TABLE IF EXISTS Crew;
DROP TABLE IF EXISTS Infrastructure;
DROP TABLE IF EXISTS Equipment;
DROP TABLE IF EXISTS Colony;
