-- 1. Names of researchers, field of research, and affiliation of their respective teams
SELECT
	R.NAME,
	R.RESEARCH_FIELD,
	C.NAME AS CREW_NAME,
	C.JOINED_DATE
FROM
	RESEARCHER R
	JOIN CREW C ON R.CREW_ID = C.CREW_ID;

-- 2. Crew names, number of equipment associated with each crew
SELECT
	C.NAME AS CREW_NAME,
	COUNT(U.EQUIPMENT_ID) AS EQUIPMENT_COUNT
FROM
	CREW C
	LEFT JOIN USES U ON C.CREW_ID = U.MISSION_ID
GROUP BY
	C.NAME
ORDER BY EQUIPMENT_COUNT DESC;

-- 3. Equipment that has been filled with more than 3 missions
SELECT
	E.NAME AS EQUIPMENT_NAME,
	COUNT(U.MISSION_ID) AS MISSION_COUNT
FROM
	EQUIPMENT E
	JOIN USES U ON E.EQUIPMENT_ID = U.EQUIPMENT_ID
GROUP BY
	E.NAME
HAVING
	COUNT(U.MISSION_ID) > 3;

-- 4. The names of the colonies established before 2010 and the area of equipment purchased for each
SELECT
	COL.NAME,
	SUM(CURRENT_DATE - E.PURCHASE_DATE) AS TOTAL_EQUIPMENT_AGE
FROM
	COLONY COL
	JOIN MISSION M ON COL.COLONY_ID = M.COLONY_ID
	JOIN USES U ON M.MISSION_ID = U.MISSION_ID
	JOIN EQUIPMENT E ON U.EQUIPMENT_ID = E.EQUIPMENT_ID
WHERE
	COL.ESTABLISHED_DATE < '2010-01-01'
GROUP BY
	COL.NAME;

-- 5. Researchers in a specific role and crews attached to them
SELECT
	R.NAME AS RESEARCHER_NAME,
	C.NAME AS CREW_NAME,
	C.ROLE
FROM
	RESEARCHER R
	JOIN CREW C ON R.CREW_ID = C.CREW_ID
WHERE
	C.ROLE = 'Engineer';

-- 6. Number of researchers on each crew
SELECT
	C.NAME AS CREW_NAME,
	COUNT(R.RESEARCHER_ID) AS RESEARCHER_COUNT
FROM
	CREW C
	LEFT JOIN RESEARCHER R ON C.CREW_ID = R.CREW_ID
GROUP BY
	C.NAME
ORDER BY RESEARCHER_COUNT DESC;

-- 7. Details of equipment purchased after 2015
SELECT
	E.NAME,
	E.PURCHASE_DATE
FROM
	EQUIPMENT E
WHERE
	E.PURCHASE_DATE > '2015-01-01';

-- 8. Information about the crews and their missions in 2019
SELECT
	C.NAME AS CREW_NAME,
	M.NAME AS MISSION_NAME,
	M.START_DATE
FROM
	CREW C
	JOIN MISSION M ON C.COLONY_ID = M.COLONY_ID
WHERE
	EXTRACT(
		YEAR
		FROM
			M.START_DATE
	) = 2019;