-- 1. מחיקת שימוש בציוד ששויך לפחות ל-2 משימות
DELETE FROM USES
WHERE
	EQUIPMENT_ID IN (
		SELECT E.EQUIPMENT_ID
		FROM EQUIPMENT E
			JOIN USES U ON E.EQUIPMENT_ID = U.EQUIPMENT_ID
		GROUP BY E.EQUIPMENT_ID
		HAVING COUNT(U.MISSION_ID) >= 2
	);

-- 2. מחיקת חוקרים שנמצאים בצוותים שמבצעים משימות אחרי 2020
DELETE FROM RESEARCHER
WHERE
	CREW_ID IN (
		SELECT C.CREW_ID
		FROM CREW C
			JOIN MISSION M ON C.COLONY_ID = M.COLONY_ID
		WHERE M.START_DATE > '2020-01-01'
	);

-- 3. מחיקת תשתיות לא פעילות מכל המושבות
DELETE FROM INFRASTRUCTURE I WHERE I.STATUS = 2;